### ISSUE TITLE
Training Strategy

### ISSUE THREAD

**Issue by 77Chen** [Ien001/AG-CNN#2]
Thank you for sharing your code. I wonder if you have followed the three-stage scheme mentioned in the original paper? Or three models trained at the same time?

**Comment by Ien001** [comment]
> Thank you for sharing your code. I wonder if you have followed the three-stage scheme mentioned in the original paper? Or three models trained at the same time?

Hi,
In my implementation, I train the three models simultaneously to build an end to end manner.
Sorry, I don’t remember the details of the paper...
