### ISSUE TITLE
torch and torchvision version

### ISSUE THREAD

**Issue by yikuan8** [Ien001/AG-CNN#3]
Thank you for your great re-implementation. 

What are the versions of torch and torchvision?

**Comment by Ien001** [comment]
> Thank you for your great re-implementation.
> 
> What are the versions of torch and torchvision?

Thanks for your question!

I think I used torch 1.0, don't remember the specific version of torchvision, sorry for that, it's long time ago...

You can check the docker container I used for this project:
https://hub.docker.com/r/ianren/cuda9.0-cudnn7.0-tf1.5-keras2.1-pytorch1.0?utm_source=docker4mac_2.2.0.0&utm_medium=repo_open&utm_campaign=referral
(You can download it and check the library version.)

Best,
Ian
