### ISSUE TITLE
image = image[int(224*0.334):int(224*0.667), int(224*0.334):int(224*0.667), :]

### ISSUE THREAD

**Issue by Kingpopen** [Ien001/AG-CNN#4]
Hello, Thank you for your reimplementation.
The Attention_gen_patchs function in train.py have the code "image = image[int(224*0.334):int(224*0.667), int(224*0.334):int(224*0.667), :]", I don't know the signification of them. Can you tell me the use of that code?

**Comment by Ien001** [comment]
> Hello, Thank you for your reimplementation.
> The Attention_gen_patchs function in train.py have the code "image = image[int(224_0.334):int(224_0.667), int(224_0.334):int(224_0.667), :]", I don't know the signification of them. Can you tell me the use of that code?

Hi, sorry for the late reply.

`image = image[int(224*0.334):int(224*0.667),int(224*0.334):int(224*0.667),:]`
is to perform center crop on the original image, which is mean to keep same setting with the image feeded to models.

For example, before we feed the models with images, we will do center crop to keep important information.
In the function `Attention_gen_patchs`, we simulate the same setting.

Best,
Ian
